// src/LanguageContext.jsx
import React, { createContext, useState, useContext } from 'react';

// 1. สร้าง Context
export const LanguageContext = createContext();

// 2. สร้าง Dictionary เก็บคำแปล
export const translations = {
  th: {
    // Sidebar.jsx
	home: "หน้าแรก",
    search: "ค้นหาสินค้า",
    cart: "ตะกร้าสินค้า",
    contact: "ติดต่อเรา",
	
	//SellerAddproduct.jsx
	back: "กลับ",
    addProduct: "เพิ่มสินค้าใหม่",
    editProduct: "แก้ไขสินค้า",
    generalInfo: "ข้อมูลทั่วไป",
    productName: "ชื่อสินค้า",
    price: "ราคา (บาท)",
    category: "หมวดหมู่",
    selectCategory: "-- เลือกหมวดหมู่ --",
    tags: "Tags (เลือกจากรายการ)",
    tagPlaceholder: "เลือกแท็ก...",
    tagSearchPlaceholder: "ค้นหา Tags...",
    preorder: "มี Pre-order",
    description: "รายละเอียดสินค้า",
    descPlaceholder: "อธิบายรายละเอียดสินค้าของคุณ...",
    productImages: "รูปภาพสินค้า",
    maxImages: "(สูงสุด 5 รูป)",
    addImg: "เพิ่มรูป",
    coverImg: "ภาพปก",
    salesInfo: "ข้อมูลการขาย",
    hasVariations: "สินค้านี้มีตัวเลือก",
    totalStock: "คลังสินค้า",
    variationTable: {
      image: "รูปภาพ",
      category: "รูปแบบ",
      option: "ชื่อตัวเลือก",
      stock: "คลังสินค้า",
      manage: "จัดการ",
      addLink: "ใส่ลิงก์รูปภาพ (URL) สำหรับตัวเลือกนี้:",
      remove: "ลบ",
      addBtn: "+ เพิ่มตัวเลือก"
    },
    cancel: "ยกเลิก",
    save: "บันทึกสินค้า",
    varname: "ชื่อรูปแบบ",
    opname: "ชื่อตัวเลือก",
    uploading: "กำลังโหลด...",
    uploadFailed: "อัปโหลดรูปล้มเหลว",
    saveSuccess: "บันทึกข้อมูลสินค้าสำเร็จ!",
    saveError: "เกิดข้อผิดพลาดในการบันทึกข้อมูล",

    // SellerCalculate.jsx
    calculate: "คำนวณราคาสินค้า",
    loading: "กำลังโหลดข้อมูล...",
    salesHistory: "ประวัติการขาย",
    allCreators: "🌟 รวมทั้งหมด",
    artist: "Creator ",
    options: "ตัวเลือก",
    stock: "คงเหลือ: ",
    total: "ยอดรวม: ",
    checkoutSuccess: "บันทึกการขายและตัดสต็อกเรียบร้อย!",
    checkoutError: "เกิดข้อผิดพลาดในการทำรายการ",
    confirmTitle: "ยืนยันการทำรายการ?",
    paymentVia: "ชำระผ่าน: ",
    totalAmountText: "ยอดชำระทั้งหมด ",
    cancel: "ยกเลิก",
    confirm: "ยืนยัน",

    // SellerCalhistory.jsx
    historyTitle: "ประวัติการขาย",
    loadingHistory: "กำลังโหลดข้อมูลประวัติ...",
    noHistory: "ยังไม่มีประวัติการขาย",
    time: "เวลา:",
    deleteBtn: "ลบทิ้ง",
    paymentMethodLabel: "ชำระผ่าน:",
    totalLabel: "ยอดรวม:",
    popupDeleteConfirmMsg: "คุณต้องการลบประวัติการขายรายการนี้ใช่หรือไม่? ข้อมูลที่ลบจะไม่สามารถกู้คืนได้",
    popupDeleteSuccessMsg: "ลบประวัติการขายเรียบร้อยแล้ว",
    popupDeleteErrorMsg: "เกิดข้อผิดพลาด ไม่สามารถลบข้อมูลได้",
    popupSuccess: "สำเร็จ",
    popupError: "ข้อผิดพลาด",
    popupConfirm: "ยืนยันการทำรายการ",
    popupAlert: "แจ้งเตือน",
    popupOk: "ตกลง",
    popupClose: "ปิด",

    // SellerCalOptionProduct.jsx
    stockLimitAlert: "สินค้านี้เหลือสต็อกเพียง ",
    unitPieces: " ชิ้น",
    selectOptionsGuide: "กรุณาเลือกตัวเลือกสินค้าที่ต้องการ",
    noImage: "ไม่มีรูปภาพ",
    stockLabel: "คงเหลือ: ",
    confirmSelection: "ยืนยันการเลือก",

    // SellerConclusion.jsx
    loadingSummary: "กำลังสรุปผลข้อมูล...",
    allCreatorsTab: "🌟 รวมทั้งหมด",
    allDays: "ทุกวัน",
    dayLabel: "วันที่",
    totalRevenueLabel: "รายได้ทั้งหมด: ",
    topUnitsSold: "🔥 3 อันดับแรก: สินค้าขายดีที่สุด",
    topRevenue: "💎 3 อันดับแรก: ยอดรวมสูงสุด",
    noSalesData: "ยังไม่มีข้อมูลการขาย",
    totalPriceText: "ยอดรวม: ",
    bahtText: " บาท",
    totalQtyText: "จำนวนรวม: ",
    categoryMix: "สัดส่วนหมวดหมู่",
    noCategoryData: "ไม่มีข้อมูลหมวดหมู่",
    outOfStockTitle: "สินค้าที่สต็อกหมด",
    colCreator: "Creator",
    colProduct: "สินค้า",
    colOption: "ตัวเลือก",
    noOutOfStock: "ขณะนี้ยังไม่มีสินค้าที่สต็อกหมด",
    dailySalesTitle: "รายงานยอดขายรายวัน",
    colDate: "วัน",
    colPrice: "ราคา",
    colQuantity: "จำนวน",
    colTotal: "รวม",
    noDailySales: "ยังไม่มีข้อมูลการขายสำหรับสินค้านี้",

    // SellerContact.jsx
    contactTitle: "ติดต่อเรา",
    reportProblem: "แจ้งปัญหาการใช้งาน :",
    suggestion: "ข้อเสนอแนะ :",

    // SellerProduct.jsx
    manageProducts: "จัดการสินค้า",
    allProductsOf: "สินค้าทั้งหมดของ ",
    addNewProductBtn: "เพิ่มสินค้าใหม่",
    colProduct: "สินค้า",
    colImage: "รูปภาพ",
    colVariation: "รูปแบบ",
    colOption: "ตัวเลือก",
    colPrice: "ราคา",
    colStock: "คลัง",
    colActions: "จัดการ",
    loadingProducts: "กำลังโหลดข้อมูลสินค้า...",
    noProducts: "คุณยังไม่มีสินค้าในระบบ",
    editBtn: "แก้ไข",
    deleteBtnp: "ลบทิ้ง",
    confirmDelete: "คุณแน่ใจหรือไม่?",
    errorDelete: "เกิดข้อผิดพลาดในการลบสินค้า",
    continueDelete: "กำลังลบ...",
    wantedToDelete1: "คุณต้องการลบ ",
    wantedToDelete2: "ใช่หรือไม่?",
    wantedToDelete: "การกระทำนี้ไม่สามารถกู้คืนได้ ",

    // SellerSidebar.jsx
    creatorPanel: "แผงควบคุมร้าน",
    menuHomepage: "หน้าร้านค้า",
    menuProduct: "จัดการสินค้า",
    menuCalculate: "คำนวณ",
    menuConclusion: "สรุปผล",
    menuContact: "ติดต่อเรา",

    // SellerStorePage.jsx
    saveBoothSuccess: "บันทึกข้อมูลหน้าร้านเรียบร้อยแล้ว!",
    saveBoothError: "เกิดข้อผิดพลาดในการบันทึกข้อมูล",
    loadingBooth: "กำลังโหลดข้อมูลบูธของคุณ...",
    boothNotFound: "ไม่พบข้อมูลบูธของคุณในระบบ",
    userNoBooth1: "ชื่อผู้ใช้ \"",
    userNoBooth2: "\" อาจยังไม่มีบูธที่ผูกไว้ในระบบ",
    popupSuccessTitle: "สำเร็จ!",
    popupErrorTitle: "เกิดข้อผิดพลาด",
    popupAlertTitle: "แจ้งเตือน",
    btnOk: "ตกลง",
    btnCancel: "ยกเลิก",
    btnSaving: "กำลังบันทึก...",
    btnSaveData: "บันทึกข้อมูล",
    btnEditBooth: "แก้ไขข้อมูลบูธ",
    placeholderCover: "วางลิงก์รูปหน้าปกใหม่ที่นี่...",
    yourBoothBadge: "YOUR BOOTH",
    placeholderDesc: "กรอกคำอธิบายบูธของคุณ...",
    noDesc: "ยังไม่มีคำอธิบายบูธ",
    productsInBooth: "สินค้าในบูธ",
    itemsCount: "รายการ",
    tabAllCreators: "🌟 รวมทั้งหมด",
    itemsLeft: "มี",
    pieces: " ชิ้น",
    noProductsFrom1: "ไม่มีสินค้าของ ",
    noProductsFrom2: " ในบูธนี้",
    downloading: "กำลังอัปโหลดรูปภาพ...",
    clickToUpload: "คลิกเพื่ออัปโหลดรูปปกใหม่",
    suggestedSize: "แนะนำสัดส่วนแนวนอน (เช่น 1500 x 500)",

    //StorePage.jsx
    boothNumber: "บูธ ",
    boothItemsTitle: "สินค้าบูธนี้",
    loadingProducts: "กำลังโหลดข้อมูลสินค้า...",
    itemsLeft: "คงเหลือ ",
    pieces: " ชิ้น",
    noProductsFrom: "ยังไม่มีสินค้าของ ",
    back: "กลับ",

    // Searchproduct.jsx
    searchingProducts: "กำลังค้นหาสินค้า...",
    searchTitle: "ค้นหาสินค้า",
    eventDayLabel: "วันที่จัดงาน",
    allDays: "ทุกวัน",
    day1: "วันที่ 1: 30 พ.ค. 2569",
    day2: "วันที่ 2: 31 พ.ค. 2569",
    zoneLabel: "โซน",
    allZones: "ทุกโซน",
    zonePrefix: "โซน ",
    categoryLabel: "หมวดหมู่",
    allCategories: "ทุกหมวดหมู่",
    tagsLabel: "แท็ก",
    filterByTags: "กรองด้วยแท็ก...",
    tagsSelected: " แท็กที่เลือก",
    searchTagsPlaceholder: "ค้นหาแท็ก...",
    searchLabel: "ค้นหา",
    searchPlaceholder: "ค้นหาด้วยชื่อสินค้า, ครีเอเตอร์ หรือบูธ...",
    unknownCreator: "ไม่ระบุชื่อนักวาด",
    availableStock: "มีสินค้า: ",
    outOfStock: "สินค้าหมด",
    noProductsFound: "ไม่พบสินค้าที่คุณกำลังมองหา",

    // ProductDetail.jsx
    defaultVariation: "ตัวเลือก",
    defaultCategory: "สินค้าทั่วไป",
    sellerModeWarning: "โหมดผู้ขาย: คุณไม่สามารถทำรายการซื้อ/จองสินค้าในบูธตัวเองได้",
    loginRequired: "กรุณาล็อกอินก่อนทำรายการ",
    selectOptionWarning: "กรุณาเลือกลายสินค้าก่อน",
    addToCartSuccess: "เพิ่มสินค้าลงตะกร้าเรียบร้อย!",
    errorPrefix: "เกิดข้อผิดพลาด: ",
    backToStore: "กลับไปหน้าร้านค้า",
    selectLabel: "เลือก",
    qtyLabel: "จำนวน",
    refStock: "มีสินค้า: ",
    pieces: " รายการ",
    patternLabel: "ลาย ",
    reserveBtn: "🔖จองไว้แล้ว",
    addingBtn: "กำลังโหลด...",
    addCartBtn: "🛒เพิ่มลงตะกร้า",
    popupSuccess: "สำเร็จ",
    popupError: "ข้อผิดพลาด",
    popupAlert: "แจ้งเตือน",
    okBtn: "ตกลง",
    cancelBtn: "ยกเลิก",
    confirmBtn: "ยืนยัน",
    confirmSelection: "ยืนยันการดำเนินการ",
    reserveConfirmTitle: "คุณได้ทำการสั่งจองสินค้านี้เพื่อไปรับหน้างานหรือจัดส่งออนไลน์แล้วใช่หรือไม่?",

    // History.jsx
    pleaseLogin: "กรุณาเข้าสู่ระบบ",
    loadingHistory: "กำลังโหลดประวัติ...",
    backToCart: "กลับไปหน้าตะกร้า",
    myHistory: "ประวัติการสั่งซื้อ",
    historyOf: "ประวัติของ ",
    totalSpent: "ยอดใช้จ่ายรวม",
    colProduct: "สินค้า",
    colType: "ประเภท",
    colPrice: "ราคา",
    colQuantity: "จำนวน",
    colTotal: "รวม",
    noHistory: "ไม่มีประวัติการทำรายการ",
    unknownBooth: "ไม่ระบุชื่อบูธ",
    boothPrefix: "บูธ: ",
    totalAmount: "ยอดรวมทั้งสิ้น",
    chooseOption: "ตัวเลือก: ",
    priceLabel: "ราคา:",
    qtyLabel: "ซื้อ:",
    totalLabel: "รวม:",

    // Cart.jsx
    confirmOrder1: "ยืนยันการสั่งซื้อสินค้าจำนวน ",
    confirmOrder2: " รายการ?",
    unknownBooth: "ไม่ระบุชื่อบูธ",
    orderSuccess: "บันทึกการสั่งซื้อเรียบร้อยแล้ว!",
    orderError: "เกิดข้อผิดพลาดในการบันทึกข้อมูล: ",
    noProductName: "ไม่มีชื่อสินค้า",
    deleteItemPrompt: "ลบรายการนี้ออกจากตะกร้าใช่หรือไม่?",
    deleteSelected1: "ต้องการลบสินค้าที่เลือกจำนวน ",
    deleteSelected2: " รายการ ใช่หรือไม่?",
    pleaseLoginCart: "กรุณาเข้าสู่ระบบเพื่อดูตะกร้าสินค้า",
    loadingCart: "กำลังโหลดตะกร้า...",
    shoppingCartOf: "ตะกร้าสินค้าของ ",
    historyBtn: "ประวัติ",
    colProduct: "สินค้า",
    colType: "ประเภท",
    colStock: "คงเหลือ",
    colQty: "จำนวน",
    colPrice: "ราคา",
    colAction: "จัดการ",
    emptyCart: "ตะกร้าของคุณว่างเปล่า",
    boothLabel: "บูธ",
    soldOut: "สินค้าหมด",
    chooseLabel: "เลือก",
    priceLabel: "ราคา:",
    qtyLabel: "จำนวน:",
    totalLabel: "รวม:",
    deleteBtn: "ลบ",
    selectOptionTitle: "เลือกตัวเลือกสินค้า",
    currentOption: "ปัจจุบัน: ",
    noOptions: "ไม่มีตัวเลือกสินค้า",
    selectPrefix: "เลือก ",
    stockLabel: "stock:",
    cancelBtn: "ยกเลิก",
    confirmBtn: "ยืนยัน",
    selectAll: "เลือกทั้งหมด",
    totalItems1: "รวม (",
    totalItems2: " รายการ):",
    checkoutConfirm: "ยืนยันการซื้อ",
    defaultVariation: "ตัวเลือก",
    popupSuccess: "สำเร็จ",
    popupError: "ข้อผิดพลาด",
    popupConfirmTitle: "ยืนยันการทำรายการ",
    popupAlert: "แจ้งเตือน",
    popupCancel: "ยกเลิก",
    popupOk: "ยืนยัน",

    //BoothMap.jsx
    emptyBooth: "บูธ",
    emptyBoothAlt: "ยังว่างอยู่",
    loading: "โหลดข้อมูลผังงาน...",
    legendReserved: "จองแล้วต้องไปรับของ",
    legendWishlist: "มีสินค้าอยู่ในWishlist",
    legendWishlistSoldout: "Wishlistบางอย่างหมดแล้ว",
    legendPartialBuy: "ซื้อไปแล้วบางส่วน",
    legendAllBuy: "ซื้อหรือรับสินค้าครบทั้งหมด",
    legendAllSoldout: "สินค้าที่Wishlistหมด",

    // AuthPopup.jsx
    authTitle: "จำเป็นต้องเข้าสู่ระบบ",
    authMessage: "คุณต้องเข้าสู่ระบบก่อนเพื่อเพิ่มสินค้าลงตะกร้าหรือจองสินค้า คุณต้องการเข้าสู่ระบบตอนนี้เลยหรือไม่?",
    authNotNow: "ไว้คราวหลัง",
    authLoginBtn: "ไปหน้าเข้าสู่ระบบ",
  },
  en: {
    	// Sidebar.jsx
    home: "Home",
    search: "Search Products",
    cart: "Shopping Cart",
    contact: "Contact Us",
	
	//SellerAddproduct.jsx
	back: "Back",
    addProduct: "Add New Product",
    editProduct: "Edit Product",
    generalInfo: "General Information",
    productName: "Product Name",
    price: "Price (Baht)",
    category: "Category",
    selectCategory: "-- Select Category --",
    tags: "Tags (Select from list)",
    tagPlaceholder: "Select tags...",
    tagSearchPlaceholder: "Search Tags...",
    preorder: "Pre-order?",
    description: "Description",
    descPlaceholder: "Describe your product details...",
    productImages: "Product Images",
    maxImages: "(Max 5 images)",
    addImg: "Image",
    coverImg: "Cover",
    salesInfo: "Sales Information",
    hasVariations: "Product has variations",
    totalStock: "Stock",
    variationTable: {
      image: "Image",
      category: "Variation",
      option: "Option",
      stock: "Stock",
      manage: "Manage",
      addLink: "Enter image URL for this option:",
      remove: "Remove",
      addBtn: "+ Add "
    },
    cancel: "Cancel",
    save: "Save Product",
    varname: "Variation Name",
    opname: "Option Name",
    uploading: "Loading...",
    uploadFailed: "Image upload failed",
    saveSuccess: "Product saved successfully!",
    saveError: "Error saving product",

    // SellerCalculate.jsx
    calculate: "Calculate total price",
    loading: "Loading data...",
    salesHistory: "Sales History",
    allCreators: "🌟 All Creators",
    artist: "Creator ",
    options: "Options",
    stock: "Stock: ",
    total: "Total: ",
    checkoutSuccess: "Sale recorded and stock updated successfully!",
    checkoutError: "An error occurred during the transaction.",
    confirmTitle: "Confirm Transaction?",
    paymentVia: "Payment via: ",
    totalAmountText: "Total amount ", // Named this way to avoid conflict with totalAmount variable
    cancel: "Cancel",
    confirm: "Confirm",

    // SellerCalhistory.jsx
    historyTitle: "History",
    loadingHistory: "Loading history...",
    noHistory: "No sales history yet",
    time: "Time:",
    deleteBtn: "Delete",
    paymentMethodLabel: "Payment via:",
    totalLabel: "Total:",
    popupDeleteConfirmMsg: "Are you sure you want to delete this sales history? This action cannot be undone.",
    popupDeleteSuccessMsg: "Sales history deleted successfully.",
    popupDeleteErrorMsg: "An error occurred. Cannot delete data.",
    popupSuccess: "Success",
    popupError: "Error",
    popupConfirm: "Confirm Action",
    popupAlert: "Alert",
    popupOk: "OK",
    popupClose: "Close",

    // SellerCalOptionProduct.jsx
    stockLimitAlert: "Stock limit reached. Only ",
    unitPieces: " items left.",
    selectOptionsGuide: "Please select your desired options",
    noImage: "No Image",
    stockLabel: "Stock: ",
    confirmSelection: "Confirm Selection",

    // SellerConclusion.jsx
    loadingSummary: "Summarizing data...",
    allCreatorsTab: "🌟 All Creators",
    allDays: "All Days",
    dayLabel: "Day",
    totalRevenueLabel: "Total Revenue: ",
    topUnitsSold: "🔥 Top 3: Most Units Sold",
    topRevenue: "💎 Top 3: Highest Revenue",
    noSalesData: "No sales data available",
    totalPriceText: "Total price: ",
    bahtText: " Baht",
    totalQtyText: "Total quantity: ",
    categoryMix: "Category Mix",
    noCategoryData: "No category data",
    outOfStockTitle: "Out of Stock Products",
    colCreator: "Creator",
    colProduct: "Product",
    colOption: "Option",
    noOutOfStock: "No out-of-stock items currently",
    dailySalesTitle: "Daily Sales Report",
    colDate: "Date",
    colPrice: "Price",
    colQuantity: "Quantity",
    colTotal: "Total",
    noDailySales: "No sales data for this item yet",

    // SellerContact.jsx, Contact.jsx
    contactTitle: "Contact us",
    reportProblem: "Report a Problem :",
    suggestion: "Suggestion :",

    // SellerProduct.jsx
    manageProducts: "Manage Products",
    allProductsOf: "All products of ",
    addNewProductBtn: "Add New Product",
    colProduct: "Product",
    colImage: "Image",
    colVariation: "Variation",
    colOption: "Option",
    colPrice: "Price",
    colStock: "Stock",
    colActions: "Actions",
    loadingProducts: "Loading product data...",
    noProducts: "You don't have any products in the system",
    editBtn: "Edit",
    deleteBtnp: "Delete",
    confirmDelete: "Are you sure?",
    errorDelete: "Error deleting product",
    continueDelete: "Deleting...",
    wantedToDelete1: "Do you want to delete ",
    wantedToDelete2: "?",
    wantedToDelete: "This action cannot be undone.",

    // SellerSidebar.jsx
    creatorPanel: "Creator Panel",
    menuHomepage: "Homepage",
    menuProduct: "Product",
    menuCalculate: "Calculate",
    menuConclusion: "Conclusion",
    menuContact: "Contact Us",

    // SellerStorePage.jsx
    saveBoothSuccess: "Booth data saved successfully!",
    saveBoothError: "Error saving booth data.",
    loadingBooth: "Loading your booth data...",
    boothNotFound: "Booth data not found",
    userNoBooth1: "User \"",
    userNoBooth2: "\" might not have a linked booth yet.",
    popupSuccessTitle: "Success!",
    popupErrorTitle: "Error",
    popupAlertTitle: "Alert",
    btnOk: "OK",
    btnCancel: "Cancel",
    btnSaving: "Saving...",
    btnSaveData: "Save Data",
    btnEditBooth: "Edit Booth Info",
    placeholderCover: "Paste new cover image URL here...",
    yourBoothBadge: "YOUR BOOTH",
    placeholderDesc: "Enter your booth description...",
    noDesc: "No booth description yet",
    productsInBooth: "Products",
    itemsCount: "items",
    tabAllCreators: "🌟 All Creators",
    itemsLeft: "stock",
    pieces: " left",
    noProductsFrom1: "No products from ",
    noProductsFrom2: " in this booth",
    downloading: "Uploading image...",
    clickToUpload: "Click to upload new cover image",
    suggestedSize: "Recommended landscape ratio (e.g. 1500 x 500)",

    //StorePage.jsx
    boothNumber: "Booth ",
    boothItemsTitle: "Booth Products",
    loadingProducts: "Loading products...",
    itemsLeft: "stock ",
    pieces: " left",
    noProductsFrom: "No products from ",
    back: "Back",

    // Searchproduct.jsx
    searchingProducts: "Searching for products...",
    searchTitle: "Search Products",
    eventDayLabel: "Event Day",
    allDays: "All Days",
    day1: "Day 1: 30 May 2026",
    day2: "Day 2: 31 May 2026",
    zoneLabel: "Zone",
    allZones: "All Zones",
    zonePrefix: "Zone ",
    categoryLabel: "Category",
    allCategories: "All Categories",
    tagsLabel: "Tags",
    filterByTags: "Filter by tags...",
    tagsSelected: " tags selected",
    searchTagsPlaceholder: "Search tags...",
    searchLabel: "Search",
    searchPlaceholder: "Search by product name, creator or booth...",
    unknownCreator: "Unknown Creator",
    availableStock: "Available: ",
    outOfStock: "Out of Stock",
    noProductsFound: "No products found matching your criteria",

    // ProductDetail.jsx
    defaultVariation: "Option",
    defaultCategory: "General",
    sellerModeWarning: "Seller Mode: You cannot purchase or reserve items from your own booth.",
    loginRequired: "Please login before proceeding.",
    selectOptionWarning: "Please select an option first.",
    addToCartSuccess: "Added to cart successfully!",
    errorPrefix: "Error: ",
    backToStore: "Back to store",
    selectLabel: "Select",
    qtyLabel: "Quantity",
    refStock: "stock: ",
    pieces: " pieces",
    patternLabel: "Option ",
    reserveBtn: "🔖Reserved",
    addingBtn: "Loading...",
    addCartBtn: "🛒Add to Cart",
    popupSuccess: "Success",
    popupError: "Error",
    popupAlert: "Alert",
    okBtn: "OK",
    cancelBtn: "Cancel",
    confirmBtn: "Confirm",
    confirmSelection: "Confirm your selection",
    reserveConfirmTitle: "Have you already reserved this item for event pickup or online delivery?",

    // History.jsx
    pleaseLogin: "Please log in.",
    loadingHistory: "Loading history...",
    backToCart: "Back to Cart",
    myHistory: "My History",
    historyOf: "History of ",
    totalSpent: "Total Spent",
    colProduct: "Product",
    colType: "Type",
    colPrice: "Price",
    colQuantity: "Quantity",
    colTotal: "Total",
    noHistory: "No transaction history",
    unknownBooth: "Unknown Booth",
    boothPrefix: "Booth: ",
    totalAmount: "Total Amount",
    chooseOption: "Option: ",
    priceLabel: "Price:",
    qtyLabel: "Qty:",
    totalLabel: "Total:",

    // Cart.jsx
    confirmOrder1: "Confirm order for ",
    confirmOrder2: " items?",
    unknownBooth: "Unknown Booth",
    orderSuccess: "Order saved successfully!",
    orderError: "Error saving order: ",
    noProductName: "No Product Name",
    deleteItemPrompt: "Delete this item from cart?",
    deleteSelected1: "Delete ",
    deleteSelected2: " selected items?",
    pleaseLoginCart: "Please log in to view your cart.",
    loadingCart: "Loading cart...",
    shoppingCartOf: "Shopping Cart of ",
    historyBtn: "History",
    colProduct: "Product",
    colType: "Type",
    colStock: "Stock",
    colQty: "Quantity",
    colPrice: "Price",
    colAction: "Action",
    emptyCart: "Your cart is empty.",
    boothLabel: "Booth",
    soldOut: "SOLD OUT",
    chooseLabel: "choose",
    priceLabel: "Price:",
    qtyLabel: "Qty:",
    totalLabel: "Total:",
    deleteBtn: "Delete",
    selectOptionTitle: "Select Option",
    currentOption: "Current: ",
    noOptions: "No options available",
    selectPrefix: "Select ",
    stockLabel: "stock:",
    cancelBtn: "CANCEL",
    confirmBtn: "CONFIRM",
    selectAll: "Select All",
    totalItems1: "Total (",
    totalItems2: " items):",
    checkoutConfirm: "Confirm Order",
    defaultVariation: "Option",
    popupSuccess: "Success",
    popupError: "Error",
    popupConfirmTitle: "Confirm Action",
    popupAlert: "Alert",
    popupCancel: "Cancel",
    popupOk: "CONFIRM",

    //BoothMap.jsx
    emptyBooth: "Booth",
    emptyBoothAlt: "Still available",
    loading: "Loading map data...",
    legendReserved: "Reserved, pending pickup",
    legendWishlist: "In Wishlist",
    legendWishlistSoldout: "Some Wishlist sold out",
    legendPartialBuy: "Partially purchased",
    legendAllBuy: "Purchased/Received",
    legendAllSoldout: "Wishlist Sold out",

    // AuthPopup.jsx
    authTitle: "Authentication Required",
    authMessage: "You must be logged in to add items to your cart or reserve an item. Would you like to sign in now?",
    authNotNow: "Not Now",
    authLoginBtn: "Go to Login",
  }
};

/// 3. สร้าง Provider Component
export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('en');

  // ฟังก์ชันช่วยดึงคำแปลไปใช้
  const t = (key) => {
    // กรณีเป็น key ชั้นเดียว เช่น t('home')
    if (translations[lang][key]) return translations[lang][key];
    
    // กรณีเรียก nested key เช่น t('variationTable').image (ถ้าคุณใช้โครงสร้างนี้ใน Sidebar)
    return key;
  };

  const toggleLang = () => {
    setLang((prev) => (prev === 'th' ? 'en' : 'th'));
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, toggleLang }}>
      {children}
    </LanguageContext.Provider>
  );
};

// 4. สร้าง Custom Hook พร้อมตัวดัก Error
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};